# Generated by Django 4.1.4 on 2022-12-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolios', '0002_usuarioip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='foto',
            field=models.CharField(max_length=400),
        ),
    ]
